name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'
        
    - name: Restore solution
      run: dotnet restore *.sln

    - name: Build solution
      run: dotnet build *.sln --configuration Release

    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with:
        registry: 'acrapidemopedrohosoares001.azurecr.io'
        username: 'acrapidemopedrohosoares001'
        password: 'KxDAGaCUgynsfa/MQc1kZQQDm6nkYkyMfh6F3iOagg+ACRAv9zvS'

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: acrapidemopedrohosoares001/api-dio-test
        tags: |
          type=schedule,pattern=latest
          type=sha,format=short
          type=ref,event=branch
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        file: ./DIOApiTemp/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
